[Runtime]
# RuntimeSize=30G
# RAM=4G
# CPUs=4

[Distribution]
Distribution=fedora
Release=44

[Build]
# ToolsTree=default
# WithNetwork=true

[Output]
Format=disk
Output=ace-os
OutputDirectory=mkosi.output
WorkspaceDirectory=mkosi.workspace
CacheDirectory=mkosi.cache
BuildDirectory=mkosi.builddir
ImageId=ace-os
CompressOutput=zstd
Bootable=yes
Bootloader=systemd-boot
RepartDirectories=mkosi.repart
KernelCommandLine=root=LABEL=ACE-ROOT-A rootflags=compress-force=zstd:1,noatime rw quiet splash

[Content]
Hostname=ace
RootPassword=ace
Autologin=yes
ExtraTrees=build-scripts:/ctx
           mkosi.extra:/
Packages=
        btrfs-progs
        dnf5
        dnf5-plugins
        dracut
        kernel
        kernel-core
        kernel-modules
        kernel-modules-core
        systemd
        systemd-boot
        systemd-resolved
        util-linux
        zstd

[Host]
QemuMem=4G
